spring.application.name=facility-access-management

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/facility_access_management}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.kgt
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.com.kgt.facility_access_management=DEBUG
