spring.application.name=facility-access-management

spring.datasource.url=jdbc:mysql://localhost:3306/facility_access_management
spring.datasource.username=root
spring.datasource.password=test1234

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.kgt
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.com.kgt.facility_access_management=DEBUG